# Generated by Django 4.1.1 on 2022-09-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_type_entry_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='MediaType',
        ),
    ]
